export const RULESET_VERSION = '1.0' as const
export const PROTOCOL_VERSION = 3 as const

export const GAME_CONFIG = {
  minPlayers: 2,
  maxPlayers: 8,
  arenaRadius: 400,
  duelHalfWidth: 400,
  duelHalfHeight: 400,
  ballRadius: 10,
  paddleRatio: 0.3,
  paddleThickness: 14,
  hardCornerRatio: 0.12,
  paddleSpeed: 360,
  startingBallSpeed: 300,
  ballAcceleration: 1.035,
  maximumBallSpeed: 720,
  orbitInfluenceRadius: 230,
  orbitCoreRadius: 38,
  wormholeMinimumGap: 260,
  modifierWarmupSeconds: 10,
  pulseMinimumGapSeconds: 7,
  pulseMaximumGapSeconds: 11,
  wormholeActivitySeconds: 14,
  wormholeMinimumGapSeconds: 3,
  wormholeMaximumGapSeconds: 12,
  orbitActivitySeconds: 11,
  orbitMinimumGapSeconds: 6,
  orbitMaximumGapSeconds: 8,
  minimumInwardComponent: 0.28,
  countdownMs: 3_000,
  transitionMs: 1_500,
  reconnectGraceMs: 10_000,
  tickRate: 60,
  snapshotRate: 20,
} as const
